### ISSUE TITLE
Flask-Ask import error. Unable to run python fils

### ISSUE THREAD

**Issue by krithi96sk** [nkp281297/Controlling-Raspberry-Pi-using-Alexa#2]

**Comment by krithi96sk** [comment]
I'm working on the installation of Flask-ask and ngrok as given in the documentation. But the system keeps throwing these errors.
```
pi@raspberrypi:~$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask_ask import Ask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/__init__.py", line 9, in <module>
    from .core import (
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 13, in <module>
    from flask import current_app, json, request as flask_request, _app_ctx_stack
  File "/usr/local/lib/python2.7/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 26, in <module>
    from . import json, cli
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 17, in <module>
    import click
ImportError: No module named click
>>>
```
It's asking me to import click, but I already have it.
```
pi@raspberrypi:~$ sudo pip install click
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: click in /usr/lib/python2.7/dist-packages (6.6)
```
I'm a beginner. Kindly help me out

**Comment by krithi96sk** [comment]
The issue is solved. Made sure click and flask were in the same python directories.
